version: '3'
services:
  spring-app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/yourdb
      SPRING_DATASOURCE_USERNAME: yourusername
      SPRING_DATASOURCE_PASSWORD: yourpassword
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_REDIS_PASSWORD: yourredispassword

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: yourmysqlrootpassword
      MYSQL_DATABASE: yourdb
      MYSQL_USER: yourusername
      MYSQL_PASSWORD: yourpassword
    ports:
      - "3306:3306"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
